# Generated by Django 4.0.3 on 2022-06-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
